from app.sqlDB.base_class import Base
from app.models.users import User
from app.models.base_info import BaseInfo
from app.models.diagnosis import Diagnosis
from app.models.diagnosis_strabismus_type_internal import DiagnosisStrabismusTypeInternal
from app.models.examination_co import ExaminationCo
from app.models.examination_nv import ExaminationNv
from app.models.examination_ro import ExaminationRo
from app.models.examination_control import ExaminationControl
from app.models.examination_cornea import ExaminationCornea
from app.models.examination_corrected_visual import ExaminationCorrectedVisual
from app.models.examination_eyeballsport import ExaminationEyeballsport
from app.models.examination_slj import ExaminationSlj
from app.models.examination_tsj import ExaminationTsj
from app.models.leave_hospital_cornea import LeaveHospitalCornea
from app.models.leave_hospital_eyeballsport import LeaveHospitalEyeballsport
from app.models.leave_hospital_lts import LeaveHospitalLts
from app.models.leave_hospital_slj import LeaveHospitalSlj
from app.models.medical_history import MedicalHistory
from app.models.surgery import Surgery
from app.models.examination_lts import ExaminationLts