"""修改部分内容2

Revision ID: 7de7547628c4
Revises: ff3325f9d614
Create Date: 2020-12-21 23:09:44.007821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7de7547628c4'
down_revision = 'ff3325f9d614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'diagnosis_strabismus_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('diagnosis_strabismus_type', mysql.VARCHAR(length=20), nullable=False, comment='斜视类型'))
    # ### end Alembic commands ###
