"""修改字段名

Revision ID: c25eb5e72683
Revises: 6198a90d51bf
Create Date: 2020-12-19 00:48:06.022498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c25eb5e72683'
down_revision = '6198a90d51bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_info', sa.Column('id', sa.VARCHAR(length=20), nullable=False, comment='基本信息id'))
    op.add_column('base_info', sa.Column('user_name', sa.VARCHAR(length=20), nullable=False, comment='姓名'))
    op.drop_column('base_info', 'base_info_id')
    op.drop_column('base_info', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_info', sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='姓名'))
    op.add_column('base_info', sa.Column('base_info_id', mysql.VARCHAR(length=20), nullable=False, comment='基本信息id'))
    op.drop_column('base_info', 'user_name')
    op.drop_column('base_info', 'id')
    # ### end Alembic commands ###
