"""empty message

Revision ID: e4fca1d6c14f
Revises: 
Create Date: 2020-12-21 14:54:43.019760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fca1d6c14f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_info',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False, comment='基本信息id'),
    sa.Column('data_type', sa.VARCHAR(length=20), nullable=False, comment='数据类别'),
    sa.Column('user_name', sa.VARCHAR(length=20), nullable=False, comment='姓名'),
    sa.Column('sex', sa.VARCHAR(length=2), nullable=False, comment='性别'),
    sa.Column('age', sa.VARCHAR(length=10), nullable=False, comment='年龄'),
    sa.Column('id_number', sa.VARCHAR(length=18), nullable=False, comment='身份证号'),
    sa.Column('phone_number', sa.VARCHAR(length=11), nullable=False, comment='手机号'),
    sa.Column('order_number', sa.VARCHAR(length=20), nullable=False, comment='登记号/顺序号'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('modify_time', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.Column('suifang', sa.DateTime(), nullable=False, comment='随访时间'),
    sa.Column('beizhu', sa.Text(), nullable=False, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('uid', sa.VARCHAR(length=20), nullable=False, comment='用户uid'),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False, comment='用户名'),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False, comment='密码'),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.VARCHAR(length=11), nullable=False, comment='手机号'),
    sa.Column('permission', sa.Integer(), nullable=False, comment='权限'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('diagnosis',
    sa.Column('diagnosis_id', sa.VARCHAR(length=20), nullable=False, comment='诊断表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('diagnosis_strabismus_type', sa.VARCHAR(length=20), nullable=False, comment='斜视类型'),
    sa.Column('latent_strabismus', sa.Boolean(), nullable=False, comment='隐斜视'),
    sa.Column('Internal_strabismus', sa.VARCHAR(length=20), nullable=False, comment='内斜视'),
    sa.Column('Exotropia', sa.VARCHAR(length=20), nullable=False, comment='外斜视'),
    sa.Column('A_V', sa.VARCHAR(length=20), nullable=False, comment='A⁃V斜视'),
    sa.Column('V', sa.VARCHAR(length=20), nullable=False, comment='垂直旋转性斜视'),
    sa.Column('S', sa.VARCHAR(length=20), nullable=False, comment='特殊类型斜视'),
    sa.Column('PS', sa.VARCHAR(length=20), nullable=False, comment='中枢性麻痹性斜视'),
    sa.Column('N', sa.VARCHAR(length=20), nullable=False, comment='眼球震颤'),
    sa.Column('other', sa.VARCHAR(length=20), nullable=False, comment='其他'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_table('examination_co',
    sa.Column('examination_co_id', sa.VARCHAR(length=20), nullable=False, comment='电脑验光表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('eye_type', sa.VARCHAR(length=10), nullable=False, comment='眼别'),
    sa.Column('ds', sa.VARCHAR(length=20), nullable=False, comment='DS'),
    sa.Column('dc', sa.VARCHAR(length=20), nullable=False, comment='DC'),
    sa.Column('a', sa.VARCHAR(length=20), nullable=False, comment='A'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_co_id')
    )
    op.create_table('examination_control',
    sa.Column('examination_control_id', sa.VARCHAR(length=20), nullable=False, comment='控制力表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('examination_Control', sa.VARCHAR(length=20), nullable=False, comment='控制力'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_control_id')
    )
    op.create_table('examination_cornea',
    sa.Column('examination_cornea_id', sa.VARCHAR(length=20), nullable=False, comment='角膜映光表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('eye_type', sa.VARCHAR(length=10), nullable=False, comment='眼别'),
    sa.Column('examination_cornea_sp', sa.VARCHAR(length=20), nullable=False, comment='水平值'),
    sa.Column('examination_cornea_cz', sa.VARCHAR(length=20), nullable=False, comment='垂直值（R/L or L/R）'),
    sa.Column('examination_cornea_cz_z', sa.VARCHAR(length=20), nullable=False, comment='0-45, >45 垂直数值'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_cornea_id')
    )
    op.create_table('examination_corrected_visual',
    sa.Column('examination_corrected_visual_id', sa.VARCHAR(length=20), nullable=False, comment='矫正视力表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('left', sa.VARCHAR(length=10), nullable=False, comment='左眼矫正视力'),
    sa.Column('right', sa.VARCHAR(length=10), nullable=False, comment='右眼矫正视力'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_corrected_visual_id')
    )
    op.create_table('examination_eyeballsport',
    sa.Column('examination_eyeballsport_id', sa.VARCHAR(length=20), nullable=False, comment='眼球运动表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('eye_type', sa.VARCHAR(length=10), nullable=False, comment='眼别'),
    sa.Column('normal', sa.Boolean(), nullable=False, comment='正常'),
    sa.Column('external_rectus', sa.VARCHAR(length=20), nullable=False, comment='\t外直肌'),
    sa.Column('internal_rectus', sa.VARCHAR(length=20), nullable=False, comment='\t内直肌'),
    sa.Column('pper_rectus', sa.VARCHAR(length=20), nullable=False, comment='上直肌'),
    sa.Column('lower_rectus', sa.VARCHAR(length=20), nullable=False, comment='下直肌'),
    sa.Column('upper_oblique', sa.VARCHAR(length=20), nullable=False, comment='上斜肌'),
    sa.Column('lower_oblique', sa.VARCHAR(length=20), nullable=False, comment='下斜肌'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_eyeballsport_id')
    )
    op.create_table('examination_nv',
    sa.Column('examination_nv_id', sa.VARCHAR(length=20), nullable=False, comment='裸眼视力表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('left', sa.VARCHAR(length=10), nullable=False, comment='裸左眼视力'),
    sa.Column('right', sa.VARCHAR(length=10), nullable=False, comment='裸右眼视力'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_nv_id')
    )
    op.create_table('examination_ro',
    sa.Column('examination_ro_id', sa.VARCHAR(length=20), nullable=False, comment='检影验光表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('eye_type', sa.VARCHAR(length=10), nullable=False, comment='眼别'),
    sa.Column('ds', sa.VARCHAR(length=20), nullable=False, comment='DS'),
    sa.Column('dc', sa.VARCHAR(length=20), nullable=False, comment='DC'),
    sa.Column('a', sa.VARCHAR(length=20), nullable=False, comment='A'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_ro_id')
    )
    op.create_table('examination_slj',
    sa.Column('examination_slj_id', sa.VARCHAR(length=20), nullable=False, comment='三棱镜表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('examination_slj_zj_near', sa.VARCHAR(length=10), nullable=False, comment='视近(直角)'),
    sa.Column('examination_slj_zj_far', sa.VARCHAR(length=20), nullable=False, comment='视远(直角)'),
    sa.Column('examination_slj_dy_near', sa.VARCHAR(length=20), nullable=False, comment='视近(等腰)'),
    sa.Column('examination_slj_dy_far', sa.VARCHAR(length=20), nullable=False, comment='视远(等腰)'),
    sa.Column('examination_slj_cz', sa.VARCHAR(length=20), nullable=False, comment='垂直三棱镜'),
    sa.Column('examination_slj_cz_z', sa.VARCHAR(length=20), nullable=False, comment='0-50'),
    sa.Column('k_method', sa.VARCHAR(length=20), nullable=False, comment='k法'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_slj_id')
    )
    op.create_table('examination_tsj',
    sa.Column('examination_tsj_id', sa.VARCHAR(length=20), nullable=False, comment='同视机表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('examination_tsj_tss', sa.Boolean(), nullable=False, comment='同时视'),
    sa.Column('examination_tsj_tss_sp', sa.VARCHAR(length=20), nullable=False, comment='同时视水平值'),
    sa.Column('examination_tsj_tss_cz', sa.VARCHAR(length=20), nullable=False, comment='\t同时视垂直值（R/L or L/R'),
    sa.Column('examination_tsj_tss_cs_z', sa.VARCHAR(length=20), nullable=False, comment='\t\t同时视垂直值具体数值'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_tsj_id')
    )
    op.create_table('leave_hospital_cornea',
    sa.Column('leave_hospital_cornea_id', sa.VARCHAR(length=20), nullable=False, comment='角膜映光(出院)表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('examination_cornea_sp', sa.VARCHAR(length=20), nullable=False, comment='水平值'),
    sa.Column('examination_cornea_cz', sa.VARCHAR(length=20), nullable=False, comment='垂直值（R/L or L/R）'),
    sa.Column('examination_cornea_cz_z', sa.VARCHAR(length=20), nullable=False, comment='0-45, >45 垂直数值'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('leave_hospital_cornea_id')
    )
    op.create_table('leave_hospital_eyeballsport',
    sa.Column('leave_hospital_eyeballsport_id', sa.VARCHAR(length=20), nullable=False, comment='眼球运动(出院)表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('eye_type', sa.VARCHAR(length=10), nullable=False, comment='眼别'),
    sa.Column('normal', sa.Boolean(), nullable=False, comment='正常'),
    sa.Column('external_rectus', sa.VARCHAR(length=20), nullable=False, comment='\t外直肌'),
    sa.Column('internal_rectus', sa.VARCHAR(length=20), nullable=False, comment='\t内直肌'),
    sa.Column('pper_rectus', sa.VARCHAR(length=20), nullable=False, comment='上直肌'),
    sa.Column('lower_rectus', sa.VARCHAR(length=20), nullable=False, comment='下直肌'),
    sa.Column('upper_oblique', sa.VARCHAR(length=20), nullable=False, comment='上斜肌'),
    sa.Column('lower_oblique', sa.VARCHAR(length=20), nullable=False, comment='下斜肌'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('leave_hospital_eyeballsport_id')
    )
    op.create_table('leave_hospital_lts',
    sa.Column('LeaveHospitalLtsid', sa.VARCHAR(length=20), nullable=False, comment='立体视(出院)表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('examination_lts_j', sa.VARCHAR(length=20), nullable=False, comment='近方随机点立体视'),
    sa.Column('examination_lts_y', sa.VARCHAR(length=20), nullable=False, comment='远方随机点立体视'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('LeaveHospitalLtsid')
    )
    op.create_table('leave_hospital_slj_id',
    sa.Column('leave_hospital_slj_id', sa.VARCHAR(length=20), nullable=False, comment='三棱镜(出院)表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('leave_hospital_slj_near', sa.VARCHAR(length=10), nullable=False, comment='视近'),
    sa.Column('leave_hospital_slj_far', sa.VARCHAR(length=20), nullable=False, comment='视远'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('leave_hospital_slj_id')
    )
    op.create_table('medical_history',
    sa.Column('medical_history_id', sa.VARCHAR(length=20), nullable=False, comment='病史表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('surgery_history', sa.Boolean(), nullable=False, comment='手术史'),
    sa.Column('glasses_history', sa.VARCHAR(length=20), nullable=False, comment='戴镜史'),
    sa.Column('amblyopia_history', sa.Boolean(), nullable=False, comment='弱视治疗'),
    sa.Column('home_history', sa.Boolean(), nullable=False, comment='家族史'),
    sa.Column('born_history', sa.Boolean(), nullable=False, comment='生产史'),
    sa.Column('surgery_history_edit', sa.Text(), nullable=False, comment='手术史补充mow_age'),
    sa.Column('mow_age', sa.Integer(), nullable=False, comment='斜视年龄'),
    sa.Column('now_wt', sa.Boolean(), nullable=False, comment='歪头'),
    sa.Column('now_fs', sa.Boolean(), nullable=False, comment='复视'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('medical_history_id')
    )
    op.create_table('surgery',
    sa.Column('surgery_id', sa.VARCHAR(length=20), nullable=False, comment='手术设计表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('surgery_yb', sa.VARCHAR(length=20), nullable=False, comment='手术设计眼别'),
    sa.Column('muscle', sa.Boolean(), nullable=False, comment='肌肉'),
    sa.Column('way', sa.VARCHAR(length=20), nullable=False, comment='方式'),
    sa.Column('value', sa.VARCHAR(length=20), nullable=False, comment='量值'),
    sa.Column('beizhu', sa.VARCHAR(length=20), nullable=False, comment='备注'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('surgery_id')
    )
    op.create_table('diagnosis_strabismus_type_internal',
    sa.Column('diagnosis_strabismus_type_internal_id', sa.VARCHAR(length=20), nullable=False, comment='内斜视表id'),
    sa.Column('diagnosis_id', sa.VARCHAR(length=20), nullable=True, comment='诊断表id'),
    sa.Column('IE', sa.VARCHAR(length=20), nullable=False, comment='先天性(婴儿型)内斜视'),
    sa.Column('CE', sa.Boolean(), nullable=False, comment='共同性内斜视'),
    sa.Column('SE', sa.VARCHAR(length=20), nullable=False, comment='继发性内斜视'),
    sa.Column('NE', sa.VARCHAR(length=20), nullable=False, comment='非共同性内斜视'),
    sa.Column('EN', sa.VARCHAR(length=20), nullable=False, comment='伴有眼球震颤的内斜视'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.diagnosis_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_strabismus_type_internal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosis_strabismus_type_internal')
    op.drop_table('surgery')
    op.drop_table('medical_history')
    op.drop_table('leave_hospital_slj_id')
    op.drop_table('leave_hospital_lts')
    op.drop_table('leave_hospital_eyeballsport')
    op.drop_table('leave_hospital_cornea')
    op.drop_table('examination_tsj')
    op.drop_table('examination_slj')
    op.drop_table('examination_ro')
    op.drop_table('examination_nv')
    op.drop_table('examination_eyeballsport')
    op.drop_table('examination_corrected_visual')
    op.drop_table('examination_cornea')
    op.drop_table('examination_control')
    op.drop_table('examination_co')
    op.drop_table('diagnosis')
    op.drop_table('user')
    op.drop_table('base_info')
    # ### end Alembic commands ###
