"""修改部分内容

Revision ID: ff3325f9d614
Revises: e4fca1d6c14f
Create Date: 2020-12-21 22:30:00.187287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff3325f9d614'
down_revision = 'e4fca1d6c14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examination_lts',
    sa.Column('examination_lts_id', sa.VARCHAR(length=20), nullable=False, comment='立体视表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('examination_lts_j', sa.VARCHAR(length=20), nullable=False, comment='近方随机点立体视'),
    sa.Column('examination_lts_y', sa.VARCHAR(length=20), nullable=False, comment='远方随机点立体视'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('examination_lts_id')
    )
    op.add_column('medical_history', sa.Column('now_age', sa.Integer(), nullable=False, comment='斜视年龄'))
    op.alter_column('medical_history', 'surgery_history_edit',
               existing_type=mysql.TEXT(),
               comment='手术史补充',
               existing_comment='手术史补充mow_age',
               existing_nullable=False)
    op.drop_column('medical_history', 'mow_age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_history', sa.Column('mow_age', mysql.INTEGER(), autoincrement=False, nullable=False, comment='斜视年龄'))
    op.alter_column('medical_history', 'surgery_history_edit',
               existing_type=mysql.TEXT(),
               comment='手术史补充mow_age',
               existing_comment='手术史补充',
               existing_nullable=False)
    op.drop_column('medical_history', 'now_age')
    op.drop_table('examination_lts')
    # ### end Alembic commands ###
